config/routes.rb
Rails.application.routes.draw do
  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

  devise_for :admin, path: 'admin', skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    root to: 'homes#top'
    resources :orders, only: [:show, :update] do
      resources :order_details, only: [:update]
    end
    resources :customers, only: [:index, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :items, except: :destroy
  end

  scope module: :public do
    root to: 'homes#top'
    get '/about' => 'homes#about', as: 'about'
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
    post 'orders/confirm' => 'orders#confirm'
    get 'orders/thanks' => 'orders#thanks'
    resources :orders, only: [:index, :new, :create, :show]
    delete 'cart_items/destroy_all' => 'cart_items#destroy_all'
    resources :cart_items, only: [:index, :update, :destroy, :create]
    get 'customers/my_page' => 'customers#show', as: 'my_page'
    get 'customers/information/edit' => 'customers#edit'
    patch 'customers/information' => 'customers#update'
    get 'customers/unsubscribe' => 'customers#unsubscribe'
    patch 'customers/withdraw' => 'customers#withdraw'
    resources :items, only: [:index, :show]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image
  belongs_to :genre
  has_many :cart_items, dependent: :destroy
  has_many :order_details

  validates :name, presence: true
  validates :introduction, presence: true
  validates :price, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :is_active, presence: true
  validates :genre_id, presence: true

  enum is_active: { available: true, unavailable: false }

  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'no_image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [600, 600]).processed
  end

  def tax_include_price
    (price * 1.1).floor
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!
  layout 'admin'

  def index
    if params[:search].present?
      @items = Item.where('name LIKE ?', "%#{params[:search]}%").page(params[:page]).per(10)
    else
      @items = Item.page(params[:page]).per(10)
    end
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      flash[:notice] = "新規登録が完了しました"
      redirect_to admin_item_path(@item)
    else
      flash.now[:danger] = "新規登録に失敗しました"
      render :new
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      flash[:notice] = "更新を保存しました"
      redirect_to admin_item_path(@item)
    else
      flash.now[:danger] = "更新の保存に失敗しました"
      render :edit
    end
  end

  private

  def item_params
    params.require(:item).permit(:name, :introduction, :genre_id, :price, :is_active)
  end
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/views/admin/items/_item_form.html.erb
<div class="mt-5">
  <%= form_with model: [:admin, item] do |f| %>
    <%= render 'layouts/error_messages', model: f.object %>
    <div class="row mb-3">
      <div class="col-2 offset-3">
        <%= f.label :image, "商品画像" %>
      </div>
      <div class="col-7">
        <%= f.file_field :image, accept: "image/*" %>
      </div>
    </div>
    <div class="row mb-3">
      <div class="col-2 offset-3">
        <%= f.label :name, "商品名" %>
      </div>
      <div class="col-7">
        <%= f.text_field :name, placeholder: "商品名", size: 37 %>
      </div>
    </div>
    <div class="row mb-3">
      <div class="col-2 offset-3">
        <%= f.label :introduction, "商品説明" %>
      </div>
      <div class="col-7">
        <%= f.text_area :introduction, placeholder: "ここに説明文を記述します", size: "40x8" %>
      </div>
    </div>
    <div class="row mb-3">
      <div class="col-2 offset-3">
        <%= f.label :genre_id, "ジャンル" %>
      </div>
      <div class="col-7 custom-select-wrapper">
        <%= f.collection_select :genre_id, Genre.all, :id, :name, { prompt: "--選択してください--" }, { class: "custom-select border-dark w-50" } %>
        <i class="fa-solid fa-caret-down custom-arrow"></i>
      </div>
    </div>
    <div class="row mb-3">
      <div class="col-2 offset-3">
        <%= f.label :price, "税抜価格" %>
      </div>
      <div class="col-7">
        <%= f.text_field :price, placeholder: "1000", size: 37 %>円
      </div>
    </div>
    <div class="row mb-3">
      <div class="col-2 offset-3">
        <%= f.label :is_active, "販売ステータス" %>
      </div>
      <div class="col-7">
        <%= f.radio_button :is_active, "available" %>
        <%= f.label :is_active_available, "販売中" %>
        　
        <%= f.radio_button :is_active, "unavailable" %>
        <%= f.label :is_active_unavailable, "販売停止中" %>
      </div>
    </div>
    <div class="row my-1">
      <div class="col-2 offset-6">
        <%= render 'submit_button', f: f, submit_label: submit_label %>
      </div>
    </div>
  <% end %>
</div>

app/views/admin/items/_submit_button.html.erb
<%= f.submit submit_label, class: "form-control btn btn-success" %>

app/views/admin/items/edit.html.erb
<div class="row mt-5">
  <div class="col-4 offset-1">
    <h3 class="bg-gray d-inline-block text-center fw-bold px-4">商品編集</h3>
  </div>
</div>
<% submit_label = "変更を保存" %>
<%= render 'item_form', item: @item, submit_label: submit_label %>

app/views/admin/items/index.html.erb
<div class="row mt-5">
  <div class="col-4 offset-1">
    <h3 class="bg-gray d-inline-block text-center fw-bold px-4">商品一覧</h3>
  </div>
  <div class="col-2 offset-5">
    <%= link_to new_admin_item_path do %>
      <i class="fa-solid fa-circle-plus rounded-circle" style="font-size:30px; color:white; background-color:black;"></i>
    <% end %>
  </div>
</div>
<div class="row mt-5">
  <div class="col">
    <table class="table">
      <thead class="bg-light">
        <tr>
          <th scope="col">商品ID</th>
          <th scope="col">商品名</th>
          <th scope="col">税抜価格</th>
          <th scope="col">ジャンル</th>
          <th scope="col">販売ステータス</th>
        </tr>
      </thead>
      <tbody class="border-bottom">
        <% @items.each do |item| %>
          <tr>
            <td><%= item.id %></td>
            <td>
              <%= link_to admin_item_path(item) do %>
               <%= item.name %>
              <% end %>
            </td>
            <td><%= item.price %></td>
            <td><%= item.genre.name %></td>
            <td class="<%= item.available? ? "text-success" : "text-secondary" %>" style="font-weight:bold;"><%= item.available? ? "販売中" : "販売停止中" %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>
<div class="row justify-content-center mt-3">
  <div class="col-3 text-center">
    <%= paginate @items, param_name: 'page' %>
  </div>
</div>

app/views/admin/items/new.html.erb
<div class="row mt-5">
  <div class="col-4 offset-1">
    <h3 class="bg-gray d-inline-block text-center fw-bold px-4">商品新規登録</h3>
  </div>
</div>
<% submit_label = "新規登録" %>
<%= render 'item_form', item: @item, submit_label: submit_label %>

app/views/admin/items/show.html.erb
<div class="row my-5">
  <div class="col-4 offset-1">
    <h3 class="bg-gray d-inline-block text-center fw-bold px-4">商品詳細</h3>
  </div>
</div>
<div class="row">
  <div class="col-4 mt-5">
    <%= image_tag @item.get_image, class: "w-100" %>
  </div>
  <div class="col-8 mt-5">
    <div class="container">
      <div class="row">
        <div class="col-3">
          <p>商品名</p>
        </div>
        <div class="col-8" style="font-size:20px;">
          <%= @item.name %>
        </div>
      </div>
      <div class="row">
        <div class="col-3">
          <p>商品説明</p>
        </div>
        <div class="col-8 text-wrap" style="font-size:20px;">
          <%= @item.introduction %>
        </div>
      </div>
      <div class="row">
        <div class="col-3">
          <p>ジャンル</p>
        </div>
        <div class="col-8" style="font-size:20px;">
          <%= @item.genre.name %>
        </div>
      </div>
      <div class="row">
        <div class="col-3">
          <p>税込価格<br>(税抜価格)</p>
        </div>
        <div class="col-8" style="font-size:20px;">
          <%= @item.tax_include_price %>
          (<%= @item.price %>) 円
        </div>
      </div>
      <div class="row">
        <div class="col-3">
          <p>販売ステータス</p>
        </div>
        <div class="col-8 <%= @item.available? ? "text-success" : "text-secondary" %>" style="font-size:20px; font-weight:bold;">
          <%= @item.available? ? "販売中" : "販売停止中" %>
        </div>
      </div>
      <div class="row mb-1">
        <div class="col-3 offset-2 mt-3" style="font-size:20px;">
          <%= link_to '編集する', edit_admin_item_path(@item), class: "form-control btn btn-success px-4" %>
        </div>
      </div>
    </div>
  </div>
</div>