config/routes.rb
Rails.application.routes.draw do
  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

  devise_for :admin, path: 'admin', skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    root to: 'homes#top'
    resources :orders, only: [:show, :update] do
      resources :order_details, only: [:update]
    end
    resources :customers, only: [:index, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :items, except: :destroy
  end

  scope module: :public do
    root to: 'homes#top'
    get '/about' => 'homes#about', as: 'about'
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
    post 'orders/confirm' => 'orders#confirm'
    get 'orders/thanks' => 'orders#thanks'
    resources :orders, only: [:index, :new, :create, :show]
    delete 'cart_items/destroy_all' => 'cart_items#destroy_all'
    resources :cart_items, only: [:index, :update, :destroy, :create]
    get 'customers/my_page' => 'customers#show', as: 'my_page'
    get 'customers/information/edit' => 'customers#edit'
    patch 'customers/information' => 'customers#update'
    get 'customers/unsubscribe' => 'customers#unsubscribe'
    patch 'customers/withdraw' => 'customers#withdraw'
    resources :items, only: [:index, :show]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :addresses
  has_many :cart_items
  has_many :orders

  def full_name
    last_name + "　" + first_name
  end
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :authenticate_admin!
  layout 'admin'
  def index
    @customers = Customer.page(params[:page])
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      flash[:notice] = "変更が保存されました"
      redirect_to admin_customer_path(@customer)
    else
      flash.now[:danger] = "変更の保存に失敗しました"
      render :edit
    end
  end

  private

  def customer_params
    params.require(:customer).permit(
      :last_name,
      :first_name,
      :last_name_kana,
      :first_name_kana,
      :postal_code,
      :address,
      :telephone_number,
      :email,
      :is_active
    )
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<div class="row mt-5">
  <div class="col-5">
    <h3 class="bg-gray d-inline-block text-center fw-bold px-4">
      <%= @customer.last_name %>
      <%= @customer.first_name %>
      <span>さんの会員情報編集</span>
    </h3>
  </div>
</div>
<div class="mt-5">
  <%= form_with model: @customer, url: admin_customer_path(@customer) do |f| %>
    <%= render 'layouts/error_messages', model: f.object %>
    <div class="row mb-3">
      <div class="col-3 pl-5">
        <%= f.label :id, "会員ID" %>
      </div>
      <div class="col-3">
        <%= @customer.id %>
      </div>
    </div>
    <div class="row mb-3">
      <div class="col-3 pl-5">
        <%= f.label :name, "氏名" %>
      </div>
      <div class="col-3">
        <%= f.text_field :last_name, class: "form-control border-dark" %>
      </div>
      <div class="col-3">
        <%= f.text_field :first_name, class: "form-control border-dark" %>
      </div>
    </div>
    <div class="row mb-3">
      <div class="col-3 pl-5">
        <%= f.label :name_kana, "フリガナ" %>
      </div>
      <div class="col-3">
        <%= f.text_field :last_name_kana, class: "form-control border-dark" %>
      </div>
      <div class="col-3">
        <%= f.text_field :first_name_kana, class: "form-control border-dark" %>
      </div>
    </div>
    <div class="row mb-3">
      <div class="col-3 pl-5">
        <%= f.label :postal_code, "郵便番号" %>
      </div>
      <div class="col-3">
        <%= f.text_field :postal_code, class: "form-control border-dark" %>
      </div>
    </div>
    <div class="row mb-3">
      <div class="col-3 pl-5">
        <%= f.label :address, "住所" %>
      </div>
      <div class="col-8">
        <%= f.text_field :address, class: "form-control border-dark" %>
      </div>
    </div>
    <div class="row mb-3">
      <div class="col-3 pl-5">
        <%= f.label :telephone_number, "電話番号" %>
      </div>
      <div class="col-3">
        <%= f.text_field :telephone_number, class: "form-control border-dark" %>
      </div>
    </div>
    <div class="row mb-3">
      <div class="col-3 pl-5">
        <%= f.label :email, "メールアドレス" %>
      </div>
      <div class="col-3">
        <%= f.text_field :email, class: "form-control border-dark" %>
      </div>
    </div>
    <div class="row mb-3">
      <div class="col-3 pl-5">
        <%= f.label :is_active, "会員ステータス" %>
      </div>
      <div class="col-3">
        <%= f.radio_button :is_active, true %>
        <%= f.label :is_active_true, "有効", class: "text-secondary" %>
        　
        <%= f.radio_button :is_active, false %>
        <%= f.label :is_active_false, "退会", class: "text-secondary" %>
      </div>
    </div>
    <div class="row mt-5">
      <div class="col-3 offset-3">
        <%= f.submit "変更を保存", class: "btn btn-success px-4 py-2" %>
      </div>
    </div>
  <% end %>
</div>

app/views/admin/customers/index.html.erb
<div class="row mt-5">
  <div class="col-4 offset-1">
    <h3 class="bg-gray d-inline-block text-center fw-bold px-4">会員一覧</h3>
  </div>
</div>
<div class="row mt-3 justify-content-center">
  <div class="col-8">
    <table class="table">
      <thead class="bg-light">
        <tr>
          <th scope="col">会員ID</th>
          <th scope="col">氏名</th>
          <th scope="col">メールアドレス</th>
          <th scope="col">ステータス</th>
        </tr>
      </thead>
      <tbody>
        <% @customers.each do |customer| %>
          <tr>
            <td>
              <%= customer.id %>
            </td>
            <td>
              <%= link_to admin_customer_path(customer) do %>
                <div class="text-dark">
                  <%= customer.last_name %>
                  <%= customer.first_name %>
                </div>
              <% end %>
            </td>
            <td>
              <%= customer.email %>
            </td>
            <td class="<%= customer.is_active ? "text-success" : "text-secondary" %>" style="font-weight:bold;">
              <%= customer.is_active ? "有効" : "退会" %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/admin/customers/show.html.erb
<div class="row mt-5">
  <div class="col-5">
    <h3 class="bg-gray d-inline-block text-center fw-bold px-4">
      <%= @customer.last_name %>
      <%= @customer.first_name %>
      <span>さんの会員詳細</span>
    </h3>
  </div>
</div>
<div class="row mt-5">
  <div class="col-3 pl-4">
    <p>会員ID</p>
    <p>氏名</p>
    <p>フリガナ</p>
    <p>郵便番号</p>
    <p>住所</p>
    <p>電話番号</p>
    <p>メールアドレス</p>
    <p>会員ステータス</p>
  </div>
  <div class="col-9">
    <p><%= @customer.id %></p>
    <p><%= @customer.last_name %>　<%= @customer.first_name %></p>
    <p><%= @customer.last_name_kana %>　<%= @customer.first_name_kana %></p>
    <p><%= @customer.postal_code %></p>
    <p><%= @customer.address %></p>
    <p><%= @customer.telephone_number %></p>
    <p><%= @customer.email %></p>
    <p class="<%= @customer.is_active ? "text-success" : "text-secondary" %>" style="font-weight:bold;"><%= @customer.is_active ? "有効" : "退会" %></p>
    <p>
      <%= link_to "編集する", edit_admin_customer_path(@customer), class: "btn btn-success mr-5" %>
      <%= link_to "注文履歴一覧を見る",  admin_root_path(customer_id: @customer.id), class: "btn btn-primary ml-5" %>
    </p>
  </div>
</div>