config/routes.rb
Rails.application.routes.draw do
  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

  devise_for :admin, path: 'admin', skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    root to: 'homes#top'
    resources :orders, only: [:show, :update] do
      resources :order_details, only: [:update]
    end
    resources :customers, only: [:index, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :items, except: :destroy
  end

  scope module: :public do
    root to: 'homes#top'
    get '/about' => 'homes#about', as: 'about'
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
    post 'orders/confirm' => 'orders#confirm'
    get 'orders/thanks' => 'orders#thanks'
    resources :orders, only: [:index, :new, :create, :show]
    delete 'cart_items/destroy_all' => 'cart_items#destroy_all'
    resources :cart_items, only: [:index, :update, :destroy, :create]
    get 'customers/my_page' => 'customers#show', as: 'my_page'
    get 'customers/information/edit' => 'customers#edit'
    patch 'customers/information' => 'customers#update'
    get 'customers/unsubscribe' => 'customers#unsubscribe'
    patch 'customers/withdraw' => 'customers#withdraw'
    resources :items, only: [:index, :show]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <ul style="list-style:none;" class="alert alert-warning">
    <% model.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% if notice %>
  <div class="alert alert-success mt-2">
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-danger mt-2">
    <%= alert %>
  </div>
<% end %>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Admin - NaganoCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <script src="https://kit.fontawesome.com/9af748410a.js" crossorigin="anonymous"></script>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="border-bottom border-dark">
      <nav class="navbar navbar-expand-lg">
        <div class="container">
          <%= link_to "LOGO", root_path, class: "navbar-brand text-center px-5 border border-dark", style: "font-size:2rem; color:black;" %>
          <span>
            <div>
              <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarNavDropdown">
                <ul class="navbar-nav ml-auto">
                  <% if admin_signed_in? %>
                    <li class="nav-item">
                      <%= link_to '商品一覧', admin_items_path, class: "nav-link btn btn-outline-custom text-dark mr-3" %>
                    </li>
                    <li class="nav-item">
                      <%= link_to '会員一覧', admin_customers_path, class: "nav-link btn btn-outline-custom text-dark mr-3" %>
                    </li>
                    <li class="nav-item">
                      <%= link_to '注文履歴一覧', admin_root_path, class: "nav-link btn btn-outline-custom text-dark mr-3" %>
                    </li>
                    <li class="nav-item">
                      <%= link_to 'ジャンル一覧', admin_genres_path, class: "nav-link btn btn-outline-custom text-dark mr-3" %>
                    </li>
                    <li class="nav-item">
                      <%= link_to 'ログアウト', destroy_admin_session_path, method: :delete, class: "nav-link btn btn-outline-custom text-dark mr-3" %>
                    </li>
                  <% else %>
                    <li class="nav-item">
                      <%= link_to 'About', about_path, class: "nav-link btn btn-outline-custom text-dark mr-3" %>
                    </li>
                    <li class="nav-item">
                      <%= link_to '商品一覧', items_path_path, class: "nav-link btn btn-outline-custom text-dark mr-3" %>
                    </li>
                    <li class="nav-item">
                      <%= link_to '新規登録', new_customer_registration_path, class: "nav-link btn btn-outline-custom text-dark mr-3" %>
                    </li>
                    <li class="nav-item">
                      <%= link_to 'ログイン', new_customer_session_path, class: "nav-link btn btn-outline-custom text-dark mr-3" %>
                    </li>
                  <% end %>
                </ul>
              </div>
            </div>
            <div class="text-right mt-3">
              <%= form_with url: admin_items_path, method: :get do |f| %>
                <%= f.text_field :search, placeholder: "Search" %>
                <%= f.submit %>
              <% end %>
            </div>
          </span>
        </div>
      </nav>
    </header>
    <main class="container">
      <%= render 'layouts/flash_messages' %>
      <%= yield %>
    </main>
    <footer class="footer border-top border-dark">
    </footer>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <script src="https://kit.fontawesome.com/9af748410a.js" crossorigin="anonymous"></script>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="border-bottom border-dark">
      <nav class="navbar navbar-expand-lg">
        <div class="container">
          <%= link_to "LOGO", root_path, class: "navbar-brand text-center px-5 border border-dark", style: "font-size:2rem; color:black;" %>
          <% if customer_signed_in? %>
            <span>ようこそ、<%= current_customer.last_name %>さん！</span>
          <% end %>
          <span>
            <div>
              <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controlls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarNavDropdown">
                <ul class="navbar-nav ml-auto">
                  <% if customer_signed_in? %>
                    <li class="nav-item">
                      <%= link_to 'マイページ', my_page_path, class: "nav-link btn btn-outline-custom text-dark mr-3" %>
                    </li>
                    <li class="nav-item">
                      <%= link_to '商品一覧', items_path, class: "nav-link btn btn-outline-custom text-dark mr-3" %>
                    </li>
                    <li class="nav-item">
                      <%= link_to 'カート', cart_items_path, class: "nav-link btn btn-outline-custom text-dark mr-3" %>
                    </li>
                    <li class="nav-item">
                      <%= link_to 'ログアウト', destroy_customer_session_path, method: :delete, class: "nav-link btn btn-outline-custom text-dark" %>
                    </li>
                  <% else %>
                    <li class="nav-item">
                      <%= link_to 'About', about_path, class: "nav-link btn btn-outline-custom text-dark mr-3" %>
                    </li>
                    <li class="nav-item">
                      <%= link_to '商品一覧', items_path, class: "nav-link btn btn-outline-custom text-dark mr-3" %>
                    </li>
                    <li class="nav-item">
                      <%= link_to '新規登録', new_customer_registration_path, class: "nav-link btn btn-outline-custom text-dark mr-3" %>
                    </li>
                    <li class="nav-item">
                      <%= link_to 'ログイン', new_customer_session_path, class: "nav-link btn btn-outline-custom text-dark" %>
                    </li>
                  <% end %>
                </ul>
              </div>
            </div>
            <div class="text-right mt-3">
              <%= form_with url: items_path, method: :get do |f| %>
                <%= f.text_field :search, placeholder: "Search" %>
                <%= f.submit %>
              <% end %>
            </div>
          </span>
        </div>
      </nav>
    </header>
    <main class="container mb-3">
      <%= render 'layouts/flash_messages' %>
      <%= yield %>
    </main>
    <footer class="footer border-top border-dark">
    </footer>
  </body>
</html>